name: Validation Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-dotnet@v1

    - name: Build
      working-directory: ./src
      run: dotnet build

    - name: Run FlUnit Tests
      working-directory: ./src/FlUnit._Tests
      run: dotnet test

    - name: Run VSTest Adapter Tests
      working-directory: ./src/FlUnit.Adapters.VSTest._Tests
      run: dotnet test